#! /bin/sh
feh --bg-fill Pictures/Wallpapers/linux.jpg
xsetroot -cursor_name left_ptr

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX 

#padding
bspc config top_padding        0 
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config window_gap         2  

#borders and gaps
bspc config borderless_monocle 	true
bspc config gapless_monocle 	true
bspc config border_width       2

#border colors
bspc config normal_border_color 	"#484848"
bspc config focused_border_color 	"#a83232"
bspc config urgent_border_color 	"#B58900"
bspc config presel_border_color 	"#26E2FF"

bspc config split_ratio          0.52

#rule display
bspc rule -a Code desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
